### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by shadowwa**
This PR update icons used in latest vim-devicons and also include update from a [PR](https://github.com/ryanoasis/vim-devicons/pull/454/files) correcting bad icons since [Nerd-fonts 3.0.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0) codepoint modification of material icons

### CODE REVIEW

**Comment by coreyja** [comment]
Hey @shadowwa thanks for the PR!

This looks great! I'll get this merged in, and get a release cut now!

**Comment by coreyja** [comment]
Released as version `0.9.0`!

Thanks again @shadowwa!! Appreciate the contribution! 🙏 

If you are interested in making more changes I'd be happy to give you access to the repo as I don't use this tool as much as I used to. Just let me know!

**Comment by shadowwa** [comment]
Thanks for the offer, I was mostly fiddling with devicon-lookup to have devicons in fzf.vim.
If you don't use this tool as much, is it because you found a better tool or you dont use fzf and vim?

**Comment by coreyja** [comment]
Awesome, thanks for the contribution in any case! 🙏 

> If you don't use this tool as much, is it because you found a better tool or you dont use fzf and vim?

I'm currently using VS Code as my main editor, so just haven't opened vim up as much recently

My vim setup does still us `devicon-lookup` as it fits my workflow best. But to be honest I don't think I really looked for a new tool after developing this one

Even though I don't use it as often, I do plan on maintaining this tool indefinitely!
Its relatively simple, and as my first Rust project it has a special place in my heart 💜


----

Shameless self plug, I did some bug fixing and refactoring of the repo on stream today.
You can check out my channel here: https://twitch.tv/coreyja
And the VOD from today at: https://www.twitch.tv/videos/1879668065

**Pull request merged**
